class JsonCleanerService {
  /// Cleans the raw response from Gemini to ensure it is valid JSON.
  /// Removes markdown code blocks and trailing commas.
  static String clean(String rawJson) {
    String cleaned = rawJson.trim();

    // Remove markdown code blocks if present
    if (cleaned.startsWith('```json')) {
      cleaned = cleaned.substring(7);
    } else if (cleaned.startsWith('```')) {
      cleaned = cleaned.substring(3);
    }

    if (cleaned.endsWith('```')) {
      cleaned = cleaned.substring(0, cleaned.length - 3);
    }

    cleaned = cleaned.trim();

    // A simple regex to remove trailing commas before closing braces/brackets
    // This handles common invalid JSON generated by LLMs.
    cleaned = cleaned.replaceAll(RegExp(r',\s*}'), '}');
    cleaned = cleaned.replaceAll(RegExp(r',\s*]'), ']');

    return cleaned;
  }
}
